name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
